<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="clix-Inspiron-7560" failures="1" tests="2" name="Test CoolOerContactForm" time="26.299" errors="0" timestamp="2021-11-07T10:52:01 IST">
  <testcase classname="com.clix.clixoerwebsite.CoolOerContactForm" name="CoolOerPageContactFormValidationWithCorrectRecords" time="13.46"/>
  <testcase classname="com.clix.clixoerwebsite.CoolOerContactForm" name="CoolOerPageContactFormValidationWithInCorrectRecords" time="7.119">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at com.clix.clixoerwebsite.CoolOerContactForm.CoolOerPageContactFormValidationWithInCorrectRecords(CoolOerContactForm.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CoolOerPageContactFormValidationWithInCorrectRecords -->
</testsuite> <!-- Test CoolOerContactForm -->
