<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="clixserver" failures="1" tests="2" name="Test CoolOerContactForm" time="27.767" errors="0" timestamp="2021-10-17T20:54:20 IST">
  <testcase classname="com.clix.clixoerwebsite.CoolOerContactForm" name="CoolOerPageContactFormValidationWithCorrectRecords" time="13.77"/>
  <testcase classname="com.clix.clixoerwebsite.CoolOerContactForm" name="CoolOerPageContactFormValidationWithInCorrectRecords" time="6.414">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at com.clix.clixoerwebsite.CoolOerContactForm.CoolOerPageContactFormValidationWithInCorrectRecords(CoolOerContactForm.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CoolOerPageContactFormValidationWithInCorrectRecords -->
</testsuite> <!-- Test CoolOerContactForm -->
