<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="clixserver" failures="1" tests="2" name="Test DomainContactForm" time="19.826" errors="0" timestamp="2021-10-17T22:51:45 IST">
  <testcase classname="com.clix.clixoerwebsite.DomainContactForm" name="domainPageContactFormValidationWithInvalidRecords" time="10.558">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at com.clix.clixoerwebsite.DomainContactForm.domainPageContactFormValidationWithInvalidRecords(DomainContactForm.java:120)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- domainPageContactFormValidationWithInvalidRecords -->
  <testcase classname="com.clix.clixoerwebsite.DomainContactForm" name="domainPageContactFormValidationWithValidRecords" time="5.671"/>
</testsuite> <!-- Test DomainContactForm -->
